export const presentationBuilderTestIds = {
  root: 'presentation-builder',
  titleRow: 'presentation-builder-title-row',
  title: 'presentation-builder-title',
  date: 'presentation-builder-date',
  languageChip: (language: string) => `presentation-builder-language-${language}`,
  templates: 'presentation-builder-templates',
  template: (templateId: string) => `presentation-builder-template-${templateId}`,
  slideCountBadge: 'presentation-builder-slide-count',
  draftAll: 'presentation-builder-draft-all',
  draftError: 'presentation-builder-draft-error',
  selectAll: 'presentation-builder-select-all',
  clear: 'presentation-builder-clear',
  group: (moduleId: string) => `presentation-builder-group-${moduleId}`,
  moduleToggle: (moduleId: string) => `presentation-builder-module-${moduleId}`,
  chart: (moduleId: string, chartId: string) => `presentation-builder-chart-${moduleId}-${chartId}`,
  notes: (moduleId: string) => `presentation-builder-notes-${moduleId}`,
  cover: 'presentation-builder-cover',
  closing: 'presentation-builder-closing',
  comments: 'presentation-builder-comments',
  footer: 'presentation-builder-footer',
  preview: 'presentation-builder-preview',
  upload: 'presentation-builder-upload',
  download: 'presentation-builder-download',
  cancel: 'presentation-builder-cancel',
  publish: 'presentation-builder-publish',
};
